apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vdt-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: # Thay bằng URL git repo của bạn
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 